data_path: /data/
dataset: ecommerce

USER_ID_FIELD: user_id
ITEM_ID_FIELD: product_id
RATING_FIELD: event_type
TIME_FIELD: event_time

load_col:
    inter: [user_id, product_id, event_type, event_time]
    user: [user_id, user_session]
    item: [product_id, category_id, category_code, price, brand]

ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 50

# model config
embedding_size: 64
hidden_size: 128
inner_size: 256
n_layers: 2
dropout_prob: 0.3
loss_type: 'CE'
mask_ratio: 0.2
hidden_act: 'gelu'

# Training config
epochs: 50
train_batch_size: 4096
learner: adam
learning_rate: 0.001
train_neg_sample_args: ~
eval_steps: 1

#Evaluation config
eval_args:
    group_by: user
    order: TO
    split: {'RS': [7,1,2]}
    mode: full
metrics: ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision', 'GAUC', 'ItemCoverage', 'AveragePopularity', 'GiniIndex', 'ShannonEntropy', 'TailPercentage']
topk: [1, 5, 10, 15]
valid_metric: MRR@10
metric_decimal_place: 4
eval_batch_size: 4096